export const PIXEL_PALETTE: Record<string, string | null> = {
  '.': null,
  K: '#121212',
  W: '#efe8d4',
  S: '#d8c59a',
  H: '#6a4a2a',
  h: '#4a2e18',
  B: '#2c4a8a',
  R: '#9a2a2a',
  G: '#5bbd5b',
  Y: '#d8c34c',
  L: '#c28866',
  P: '#d9a8b3',
  T: '#7a6b4a',
  D: '#3a4a3a',
  m: '#2a2a2a',
  g: '#8a8a8a',
  U: '#5a3a7a',
  C: '#5ad0d8',
  O: '#e08a3a',
  F: '#ffc1d2',
  N: '#1a1a1a',
  o: '#6a4a2a',
  '-': '#1a1a1a',
};

export const FACES = {
  pl_normal: [
    '................',
    '.....KKKKKKK....',
    '....KSSSSSSSK...',
    '...KSWWSSWWSSK..',
    '...KSWKSSWKSSK..',
    '...KSSSSHSSSSK..',
    '...KSSSHHHSSSK..',
    '...KSSShhhSSSK..',
    '...KKSShhhSSKK..',
    '....KSSSSSSSK...',
    '....KDDDDDDDDK..',
    '...KDTTTTTTTTDK.',
    '...KDTWWWWWWTDK.',
    '...KDTWWWWWWTDK.',
    '...KDTTTTTTTTDK.',
    '....KKKKKKKKKK..',
  ],
  pl_tired: [
    '................',
    '.....KKKKKKK....',
    '....KSSSSSSSK...',
    '...KSSSSSSSSSK..',
    '...KSS--S--SSK..',
    '...KSSSSHSSSSK..',
    '...KSSSHHHSSSK..',
    '...KSSSh-hSSSK..',
    '...KKSSS-SSSKK..',
    '....KSSSSSSSK...',
    '....KDDDDDDDDK..',
    '...KDTTTTTTTTDK.',
    '...KDTWWWWWWTDK.',
    '...KDTWWWWWWTDK.',
    '...KDTTTTTTTTDK.',
    '....KKKKKKKKKK..',
  ],
  pl_greedy: [
    '................',
    '.....KKKKKKK....',
    '....KSSSSSSSK...',
    '...KSWYSSWYSSK..',
    '...KSYKSSYKSSK..',
    '...KSSSSHSSSSK..',
    '...KSSYHHYSSSK..',
    '...KSSYhhhYSSK..',
    '...KKSSYhhYSKK..',
    '....KSSYYYYSK...',
    '....KDDYYYYDDK..',
    '...KDTTTYTTTTDK.',
    '...KDTWYWYWWTDK.',
    '...KDTWWYYWWTDK.',
    '...KDTTTTTTTTDK.',
    '....KKKKKKKKKK..',
  ],
  pl_surprised: [
    '................',
    '.....KKKKKKK....',
    '....KSSSSSSSK...',
    '...KSWWSSWWSSK..',
    '...KSWNSSWNSSK..',
    '...KSSSSHSSSSK..',
    '...KSSSHHHSSSK..',
    '...KSSKoooKSSK..',
    '...KKSKoooKSKK..',
    '....KSKoooKSK...',
    '....KDDDDDDDDK..',
    '...KDTTTTTTTTDK.',
    '...KDTWWWWWWTDK.',
    '...KDTWWWWWWTDK.',
    '...KDTTTTTTTTDK.',
    '....KKKKKKKKKK..',
  ],
  pl_panicked: [
    '................',
    '....KKKKKKKKK...',
    '...KSSSSSSSSSK..',
    '..KSWWSSSWWSSSK.',
    '..KSWNSSSWNSSSK.',
    '..KSSSSSHSSSSSK.',
    '..KSSSSHHHSSSSK.',
    '..KSSSWSSSWSSSK.',
    '..KSSSWKKKWSSSK.',
    '..KKSSSKKKSSSKK.',
    '....KDDDDDDDDK..',
    '...KDTTTTTTTTDK.',
    '...KDTYWWWWYTDK.',
    '...KDTWWWWWWTDK.',
    '...KDTTTTTTTTDK.',
    '....KKKKKKKKKK..',
  ],
  helena: [
    '................',
    '....KKKKKKKKK...',
    '...KmmmmmmmmmK..',
    '..KmSSSSSSSSSmK.',
    '..KmSSSKKKSSSmK.',
    '..KmSKWKKKWKSmK.',
    '..KmSKWRKKRWKSm.',
    '..KmSSSSRSSSSSmK',
    '..KmSSKoooKSSSmK',
    '..KmmKKKKKKKmmmK',
    '..KDDDDDDDDDDDK.',
    '.KDTYYDDDDDDYYDK',
    '.KDTYWWDDDDWWYDK',
    '.KDTYYDDDDDDYYDK',
    '.KDTTTTTTTTTTTDK',
    '..KKKKKKKKKKKKK.',
  ],
  officer: [
    '................',
    '....KKKKKKKKK...',
    '...KSSSSSSSSSK..',
    '...KSWWSSWWSSSK.',
    '...KSWNSSWNSSSK.',
    '...KSSSSHSSSSSK.',
    '...KSSSSSSSSSSK.',
    '...KSKKKKKKKKSK.',
    '...KSKWWWWWWKSK.',
    '...KKKKKKKKKKKK.',
    '...KBBBBBBBBBBK.',
    '..KBBWWYYYYWWBBK',
    '..KBBWWBBBBWWBBK',
    '..KBBBBBBBBBBBBK',
    '..KBBBBBBBBBBBBK',
    '...KKKKKKKKKKKK.',
  ],
  blorg: [
    '................',
    '....UUUUUUUU....',
    '...UUCCCCCCUU...',
    '..UUCCCCCCCCUU..',
    '..UCCWKWKWCCUU..',
    '..UCCNKNKNCCUU..',
    '..UUCCCKCCCCUU..',
    '...UCCHHHHCCU...',
    '...UCCCCCCCU....',
    '....UUUUUUU.....',
    '.....UCU........',
    '....UCCCU.......',
    '...UCCCCCU......',
    '..UCCCCCCCU.....',
    '..UCCCCCCCU.....',
    '...UUUUUUUU.....',
  ],
  arbiter: [
    '................',
    '....KKKKKKKKK...',
    '...KNNNNNNNNNK..',
    '..KNYNNNNNYNNK..',
    '..KNYNWKWKWNYNK.',
    '..KNNNNKKKNNNNK.',
    '..KNSSNHNHNSSNK.',
    '..KNSSNNSNNSSNK.',
    '..KNNNNNSNNNNNK.',
    '..KmmmmmmmmmmmK.',
    '.KmYYmmmmmmmYYmK',
    '.KmYmmmmmmmmmYmK',
    '.KmYmmmYYmmmmYmK',
    '.KmmmmYYYYmmmmmK',
    '.KmmmmmmmmmmmmmK',
    '..KKKKKKKKKKKKK.',
  ],
} as const satisfies Record<string, readonly string[]>;

export type FaceId = keyof typeof FACES;
